navbar:
  displayTitle: true
  displayLogo: true
  logo:
    path: favicon.svg
    link: /
    width: 40
    height: 40
theme:
  default: dark
  displayToggle: true
displayUpdatedDate: true
dateFormat: "January 2, 2006"

blog:
  list:
    displayTags: true
toc:
  displayTags: true
